### ISSUE TITLE
Calling Rotation after the transform leads to an error

### ISSUE THREAD

**Issue by rakeshchada** [Sara-Ahmed/SiT#10]
I think the [recent commit](https://github.com/Sara-Ahmed/SiT/commit/ffc7317f046bc21498356355c4e947504677f630) to "datasets_utils.py" introduces an error as the input to the "RandomRotation" call would now be a tensor (because of the "ToTensor" transform call before) instead of a PIL Image.

The error message is listed below:

```
TypeError: transpose() received an invalid combination of arguments - got (int), but expected one of:
 * (name dim0, name dim1)
 * (int dim0, int dim1)
```

**Comment by Sara-Ahmed** [comment]
Sorry for my late response. I did not have time to debug at that time, just the rotation function need to be changed to rotate a tensor instead of PIL. Will fix it now.

Thanks a lot.
