### ISSUE TITLE
Random Erase is erroneously not being used during SSL training

### ISSUE THREAD

**Issue by mattroos** [Sara-Ahmed/SiT#13]
Why is Random Erase not being used during SSL training? It seems that it is erroneously being turned off in ```main.py```. See where ```args.reprob``` and ```args.recount``` are set to 0.

https://github.com/Sara-Ahmed/SiT/blob/1aacd6adcd39b71efc903d16b4e9095b97dda76f/main.py#L182-L186

**Comment by Sara-Ahmed** [comment]
Thanks mattroos for your interest in the work. We are applying random erase and random replace during training of SSL(). We need the original image and the erased image, therefore the erased function is not added to the transformations.

**Comment by mattroos** [comment]
Oh. I see. You do the erase/replace in the `train_SSL()` function, correct? Here...
https://github.com/Sara-Ahmed/SiT/blob/1aacd6adcd39b71efc903d16b4e9095b97dda76f/engine.py#L127

**Comment by Sara-Ahmed** [comment]
Exactly ..
