### ISSUE TITLE
How to see the image reconstruction task results

### ISSUE THREAD

**Issue by E-Loba** [Sara-Ahmed/SiT#16]
The usage example shows how to finetune the classifier head of the model in the command line, but I'm not sure how to get the reconstructed image from this output.
Can you please provide a code sample for image reconstruction?
Which part of the model output can be used to visually represent inference results like in the diagram?

**Comment by Sara-Ahmed** [comment]
Dear E-loba,

the forward function in the vision transformer class returns x_rec as well, which is the reconstructed image.

**Comment by E-Loba** [comment]
I see!
Thank you very much.
Should any additional transformation be applied to the output, just in case?

**Comment by Sara-Ahmed** [comment]
You are welcome. No transformation is required, x_rec is a tensor that suppose to be directly similar to x which is the input Image

Please refer to evaluate_SSL() function.
https://github.com/Sara-Ahmed/SiT/blob/1aacd6adcd39b71efc903d16b4e9095b97dda76f/engine.py#L272

**Comment by E-Loba** [comment]
I'll check it out.
Appreciate the swift reply and thank you for sharing the code!
