### ISSUE TITLE
ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by tianyu0207** [Sara-Ahmed/SiT#2]
Hi Thanks for the nice work. I tried to trained the network on my own dataset. However, I got the issue below. 

Traceback (most recent call last):
  File "/home/Project/SiT/main.py", line 397, in <module>
    main(args)
  File "/home/Project/SiT/main.py", line 343, in main
    args.clip_grad, model_ema, mixup_fn)
  File "/home/Project/SiT/engine.py", line 125, in train_SSL
    for imgs1, rots1, imgs2, rots2 in metric_logger.log_every(data_loader, print_freq, header):
  File "/home/Project/SiT/utils.py", line 164, in log_every
    header, total_time_str, total_time / len(iterable)))
ZeroDivisionError: float division by zero

It seems like the iterable is alway 0 somehow, and I checked my data loader, there are thousands of data available.

**Comment by Sara-Ahmed** [comment]
Would you please share your batch size? Besides, do you get this error in the first iteration or later on?

**Comment by tianyu0207** [comment]
> Would you please share your batch size? Besides, do you get this error in the first iteration or later on?

Thanks for the quick reply. 
My batch size is 64 and i got this since the first iteration.

**Comment by tianyu0207** [comment]
> since

Hi I think I fixed the issue. Thanks.

**Comment by Sara-Ahmed** [comment]
In this case, I suspect something related to the data loader. Because, the loader will return None if it is not able to get the items correctly.
If you would like, you can share with us your data loader class. Also, I would suggest you to debug the getitem() function.

**Comment by tianyu0207** [comment]
> In this case, I suspect something related to the data loader. Because, the loader will return None if it is not able to get the items correctly.
> If you would like, you can share with us your data loader class. Also, I would suggest you to debug the getitem() function.

Thanks. The problem is from getitem(). I have fixed the issue.
