### ISSUE TITLE
Can I run on single GPU machine ?

### ISSUE THREAD

**Issue by ramdhan1989** [Sara-Ahmed/SiT#23]
can I use the code to train in single GPU machine rtx5000?if yes, how to do it ?

**Comment by Sara-Ahmed** [comment]
Sure, you can either change number of process to one like that
`python -m torch.distributed.launch --nproc_per_node=1 --use_env main.py --batch-size 72 --epochs 501

or you can lunch without distributed directly like that
python  main.py --batch-size 72 --epochs 501 --min-lr 5e-6 --lr 1e-3

**Comment by ramdhan1989** [comment]
Thank you very much

**Comment by ramdhan1989** [comment]
> I just run this `python main.py --batch-size 72 --epochs 501 --min-lr 5e-6 --lr 1e-3 `but it gives an error 
`RuntimeError: Dataset not found or corrupted. You can use download=True to download it`

**Comment by ramdhan1989** [comment]
solved by adding download=download  `super(STL10, self).__init__(root, transform=transform,target_transform=target_transform, download=download)`
