### ISSUE TITLE
Get latent feature space

### ISSUE THREAD

**Issue by ramdhan1989** [Sara-Ahmed/SiT#25]
Hi, I would like to get latent feature space. From my understanding, I can take the output from here `x = self.forward_features(x)` in forward. am I correct ?

![image](https://user-images.githubusercontent.com/41245856/155889991-3460682e-53a0-4391-9cb3-47eabc8e5f72.png)

Thank you

**Comment by Sara-Ahmed** [comment]
Yes it is. Good luck!
