### ISSUE TITLE
patch size on CIFAR100

### ISSUE THREAD

**Issue by ShoufaChen** [Sara-Ahmed/SiT#27]
Hi, @Sara-Ahmed 

Thanks for your great work.

How do you deal with the CIFAR100 (32x32 image size)?

Adjust patch size or just resize the input image to 224x224 first?

**Comment by Sara-Ahmed** [comment]
Thanks for your interest in the work. You can actually do both, use the default patch size with 16x16 or reduce the patch size in use 32x32 resolution.

For more flexibility, please refer to https://github.com/Sara-Ahmed/GMML
