### ISSUE TITLE
why 3 tasks/objectives?

### ISSUE THREAD

**Issue by mywebinfo65536** [Sara-Ahmed/SiT#29]
Hi, I was reading your paper these days, but i don't really understand why you setted 3 tasks/objectives(named image reconstruction,contrastive predition and rotation prediction), what are the purposes ?  thanks

**Comment by Sara-Ahmed** [comment]
Thanks for your interest in our work. The main task is GMML, and if you can refer to "GMML is all you need" paper for more insights.
The SimCLR is to have a global representation that enforce notion of similarity/dissimilarity between positive and negative pairs.
As for Rotation, it is pretext task to encourage the network to understand the structure of the objects, as if the network correctly classified that the object is upside down, that means it understands how the object should look like. But, the rotation can be incorporated with the simclr task, and actually this what we did in the recent version (repo will be updated soon).
