### ISSUE TITLE
Questions about updated code

### ISSUE THREAD

**Issue by roshankern** [Sara-Ahmed/SiT#30]
Hello @Sara-Ahmed,

Thank you for posting the PyTorch implementation of SiT! It seems like the current commit is unable to run, and I see in https://github.com/Sara-Ahmed/SiT/issues/28 you mention you will update the github soon. I have tried running the code from commit 1aacd6adcd39b71efc903d16b4e9095b97dda76f and have nearly gotten the pre-training working. However, I can't find a version of `torchvision` that works with my GPU (GeForce RTX 3060 sm_86) and the SiT code from this commit. I have to update timm to version 0.4.12 to avoid [this error](https://github.com/qubvel/segmentation_models.pytorch/issues/424) which seems to break functionality with your code.

Do you think this will be fixed in the next release of SiT code on github? Also, you could please include all package versions used in [requirements.txt](https://github.com/Sara-Ahmed/SiT/blob/main/requirements.txt) (or include a copy of `pip freeze`)?

Thank you for all your help!
Roshan

**Comment by Sara-Ahmed** [comment]
Thanks a lot for your interest. The code will be updated soon. 
Meanwhile, please refer to GMML repo. https://github.com/Sara-Ahmed/GMML 
it is much better for small datasets

I think you will not experience these issues with GMML, but if still, please comment there and I will include a copy of pip freeze.
