### ISSUE TITLE
Fine-tuning settings

### ISSUE THREAD

**Issue by arkel23** [Sara-Ahmed/SiT#34]
First of all, great job! I just finished reading the paper, but could not find details regarding the fine-tuning settings on small-scale datasets. In particular, optimizer, number of epochs, and data augmentations when fine-tuning the SiT models pre-trained either on the same datasets or on ImageNet. If you could post those details it would make it easier to reproduce results. Thanks!

**Comment by Sara-Ahmed** [comment]
Thanks a lot Edwin for your interest in the work. 
For the finetuning, we used [Deit](https://github.com/facebookresearch/deit)  code without any parameter optimisation with one GPU for small datasets.
