### ISSUE TITLE
checkpoints

### ISSUE THREAD

**Issue by Booooooooooo** [Sara-Ahmed/SiT#5]
Thank you for your excellent work! I am interested in fine-tuning SiT for other tasks. Will you consider providing the pre-trained models?

**Comment by Sara-Ahmed** [comment]
Thanks a lot. Of course. We trained SiT on CIFAR10, CIFAR100, STL10, TinyImageNet, and 10% of ImageNet. We did not manage to train the network on full ImageNet as it is computationally expensive.

**Comment by Sara-Ahmed** [comment]
Added!
